variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "24.0.0"
  ANDROID_SDK_TOOLS: "24.4.1"

before_script:
  - cd ./DeliverResto
  - export ANDROID_HOME=/android-sdk-linux
  - export PATH=$PATH:/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew

stages:
  #- build
  #- quality_assurance
  - test



#build:
  #stage: build
  #only:
  #  - test_unit
  #script:
  #  - ./gradlew assembleDebug
  #artifacts:
  #  paths:
  #  - DeliverResto/app/build/outputs/



#verifications:
#  stage: quality_assurance
 # only:
  #  - test_unit
#  script:
#    - ./gradlew assemble lint
#    - ./gradlew findbugs
#    - ./gradlew pmd
#  artifacts:
 #   when: always
 #   paths:
 #     - DeliverResto/app/build/reports/



unitUITests:
  stage: test
  only:
    - test_unit
  # only:
  #   - tags
  script:
    - $ANDROID_HOME/tools/emulator-x86 -avd Nexus5 -no-window -no-audio -gpu auto -qemu -enable-kvm  &
    - $ANDROID_HOME/../android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew connectedAndroidTest
  artifacts:
      when: on_failure
      paths:
        - DeliverResto/app/build/reports/androidTests/connected/
